# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `WordCount.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module WordCounter
_M_WordCounter = Ice.openModule('WordCounter')
__name__ = 'WordCounter'

if '_t_StringList' not in _M_WordCounter.__dict__:
    _M_WordCounter._t_StringList = IcePy.defineSequence('::WordCounter::StringList', (), IcePy._t_string)

if '_t_WordCountMap' not in _M_WordCounter.__dict__:
    _M_WordCounter._t_WordCountMap = IcePy.defineDictionary('::WordCounter::WordCountMap', (), IcePy._t_string, IcePy._t_int)

if 'SearchResult' not in _M_WordCounter.__dict__:
    _M_WordCounter.SearchResult = Ice.createTempClass()
    class SearchResult(object):
        def __init__(self, counts=None, contexts=None):
            self.counts = counts
            self.contexts = contexts

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_WordCounter.SearchResult):
                return NotImplemented
            else:
                if self.counts != other.counts:
                    return False
                if self.contexts != other.contexts:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_WordCounter._t_SearchResult)

        __repr__ = __str__

    _M_WordCounter._t_SearchResult = IcePy.defineStruct('::WordCounter::SearchResult', SearchResult, (), (
        ('counts', (), _M_WordCounter._t_WordCountMap),
        ('contexts', (), _M_WordCounter._t_StringList)
    ))

    _M_WordCounter.SearchResult = SearchResult
    del SearchResult

_M_WordCounter._t_Worker = IcePy.defineValue('::WordCounter::Worker', Ice.Value, -1, (), False, True, None, ())

if 'WorkerPrx' not in _M_WordCounter.__dict__:
    _M_WordCounter.WorkerPrx = Ice.createTempClass()
    class WorkerPrx(Ice.ObjectPrx):

        def searchWordsWithContext(self, filepath, words, context=None):
            return _M_WordCounter.Worker._op_searchWordsWithContext.invoke(self, ((filepath, words), context))

        def searchWordsWithContextAsync(self, filepath, words, context=None):
            return _M_WordCounter.Worker._op_searchWordsWithContext.invokeAsync(self, ((filepath, words), context))

        def begin_searchWordsWithContext(self, filepath, words, _response=None, _ex=None, _sent=None, context=None):
            return _M_WordCounter.Worker._op_searchWordsWithContext.begin(self, ((filepath, words), _response, _ex, _sent, context))

        def end_searchWordsWithContext(self, _r):
            return _M_WordCounter.Worker._op_searchWordsWithContext.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_WordCounter.WorkerPrx.ice_checkedCast(proxy, '::WordCounter::Worker', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_WordCounter.WorkerPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::WordCounter::Worker'
    _M_WordCounter._t_WorkerPrx = IcePy.defineProxy('::WordCounter::Worker', WorkerPrx)

    _M_WordCounter.WorkerPrx = WorkerPrx
    del WorkerPrx

    _M_WordCounter.Worker = Ice.createTempClass()
    class Worker(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::WordCounter::Worker')

        def ice_id(self, current=None):
            return '::WordCounter::Worker'

        @staticmethod
        def ice_staticId():
            return '::WordCounter::Worker'

        def searchWordsWithContext(self, filepath, words, current=None):
            raise NotImplementedError("servant method 'searchWordsWithContext' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_WordCounter._t_WorkerDisp)

        __repr__ = __str__

    _M_WordCounter._t_WorkerDisp = IcePy.defineClass('::WordCounter::Worker', Worker, (), None, ())
    Worker._ice_type = _M_WordCounter._t_WorkerDisp

    Worker._op_searchWordsWithContext = IcePy.Operation('searchWordsWithContext', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_WordCounter._t_StringList, False, 0)), (), ((), _M_WordCounter._t_SearchResult, False, 0), ())

    _M_WordCounter.Worker = Worker
    del Worker

# End of module WordCounter
