//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `WordCount.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <WordCount.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_WordCounter_Worker_ids[2] =
{
    "::Ice::Object",
    "::WordCounter::Worker"
};
const ::std::string iceC_WordCounter_Worker_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "searchWordsWithContext"
};
const ::std::string iceC_WordCounter_Worker_searchWordsWithContext_name = "searchWordsWithContext";

}

bool
WordCounter::Worker::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_WordCounter_Worker_ids, iceC_WordCounter_Worker_ids + 2, s);
}

::std::vector<::std::string>
WordCounter::Worker::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_WordCounter_Worker_ids[0], &iceC_WordCounter_Worker_ids[2]);
}

::std::string
WordCounter::Worker::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
WordCounter::Worker::ice_staticId()
{
    static const ::std::string typeId = "::WordCounter::Worker";
    return typeId;
}

/// \cond INTERNAL
bool
WordCounter::Worker::_iceD_searchWordsWithContext(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_filepath;
    StringList iceP_words;
    istr->readAll(iceP_filepath, iceP_words);
    inS.endReadParams();
    SearchResult ret = this->searchWordsWithContext(::std::move(iceP_filepath), ::std::move(iceP_words), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
WordCounter::Worker::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_WordCounter_Worker_ops, iceC_WordCounter_Worker_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_WordCounter_Worker_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_searchWordsWithContext(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
WordCounter::WorkerPrx::_iceI_searchWordsWithContext(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::WordCounter::SearchResult>>& outAsync, const ::std::string& iceP_filepath, const StringList& iceP_words, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_WordCounter_Worker_searchWordsWithContext_name);
    outAsync->invoke(iceC_WordCounter_Worker_searchWordsWithContext_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_filepath, iceP_words);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
WordCounter::WorkerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<WorkerPrx>();
}
/// \endcond

const ::std::string&
WordCounter::WorkerPrx::ice_staticId()
{
    return Worker::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_WordCounter_Worker_searchWordsWithContext_name = "searchWordsWithContext";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::WordCounter::upCast(Worker* p) { return p; }

void
::IceProxy::WordCounter::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Worker>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Worker;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::WordCounter::Worker::_iceI_begin_searchWordsWithContext(const ::std::string& iceP_filepath, const ::WordCounter::StringList& iceP_words, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_WordCounter_Worker_searchWordsWithContext_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_WordCounter_Worker_searchWordsWithContext_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_WordCounter_Worker_searchWordsWithContext_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_filepath);
        ostr->write(iceP_words);
        result->endWriteParams();
        result->invoke(iceC_WordCounter_Worker_searchWordsWithContext_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::WordCounter::SearchResult
IceProxy::WordCounter::Worker::end_searchWordsWithContext(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_WordCounter_Worker_searchWordsWithContext_name);
    ::WordCounter::SearchResult ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::WordCounter::Worker::_newInstance() const
{
    return new Worker;
}
/// \endcond

const ::std::string&
IceProxy::WordCounter::Worker::ice_staticId()
{
    return ::WordCounter::Worker::ice_staticId();
}

WordCounter::Worker::~Worker()
{
}

/// \cond INTERNAL
::Ice::Object* WordCounter::upCast(Worker* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_WordCounter_Worker_ids[2] =
{
    "::Ice::Object",
    "::WordCounter::Worker"
};

}

bool
WordCounter::Worker::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_WordCounter_Worker_ids, iceC_WordCounter_Worker_ids + 2, s);
}

::std::vector< ::std::string>
WordCounter::Worker::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_WordCounter_Worker_ids[0], &iceC_WordCounter_Worker_ids[2]);
}

const ::std::string&
WordCounter::Worker::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
WordCounter::Worker::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::WordCounter::Worker";
    return typeId;
#else
    return iceC_WordCounter_Worker_ids[1];
#endif
}

/// \cond INTERNAL
bool
WordCounter::Worker::_iceD_searchWordsWithContext(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_filepath;
    StringList iceP_words;
    istr->read(iceP_filepath);
    istr->read(iceP_words);
    inS.endReadParams();
    SearchResult ret = this->searchWordsWithContext(iceP_filepath, iceP_words, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_WordCounter_Worker_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "searchWordsWithContext"
};

}

/// \cond INTERNAL
bool
WordCounter::Worker::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_WordCounter_Worker_all, iceC_WordCounter_Worker_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_WordCounter_Worker_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_searchWordsWithContext(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
WordCounter::Worker::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Worker, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
WordCounter::Worker::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Worker, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
WordCounter::_icePatchObjectPtr(WorkerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = WorkerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Worker::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
