//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `WordCount.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __WordCount_h__
#define __WordCount_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace WordCounter
{

class Worker;
class WorkerPrx;

}

namespace WordCounter
{

using StringList = ::std::vector<::std::string>;

using WordCountMap = ::std::map<::std::string, int>;

struct SearchResult
{
    ::WordCounter::WordCountMap counts;
    ::WordCounter::StringList contexts;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::WordCounter::WordCountMap&, const ::WordCounter::StringList&> ice_tuple() const
    {
        return std::tie(counts, contexts);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace WordCounter
{

class Worker : public virtual ::Ice::Object
{
public:

    using ProxyType = WorkerPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual SearchResult searchWordsWithContext(::std::string chunk, StringList words, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_searchWordsWithContext(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace WordCounter
{

class WorkerPrx : public virtual ::Ice::Proxy<WorkerPrx, ::Ice::ObjectPrx>
{
public:

    SearchResult searchWordsWithContext(const ::std::string& chunk, const StringList& words, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::WordCounter::SearchResult>(true, this, &WorkerPrx::_iceI_searchWordsWithContext, chunk, words, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto searchWordsWithContextAsync(const ::std::string& chunk, const StringList& words, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::WordCounter::SearchResult>>().get_future())
    {
        return _makePromiseOutgoing<::WordCounter::SearchResult, P>(false, this, &WorkerPrx::_iceI_searchWordsWithContext, chunk, words, context);
    }

    ::std::function<void()>
    searchWordsWithContextAsync(const ::std::string& chunk, const StringList& words,
                                ::std::function<void(::WordCounter::SearchResult)> response,
                                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                                ::std::function<void(bool)> sent = nullptr,
                                const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::WordCounter::SearchResult>(std::move(response), std::move(ex), std::move(sent), this, &WordCounter::WorkerPrx::_iceI_searchWordsWithContext, chunk, words, context);
    }

    /// \cond INTERNAL
    void _iceI_searchWordsWithContext(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::WordCounter::SearchResult>>&, const ::std::string&, const StringList&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    WorkerPrx() = default;
    friend ::std::shared_ptr<WorkerPrx> IceInternal::createProxy<WorkerPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits<::WordCounter::SearchResult>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 2;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::WordCounter::SearchResult, S>
{
    static void read(S* istr, ::WordCounter::SearchResult& v)
    {
        istr->readAll(v.counts, v.contexts);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace WordCounter
{

using WorkerPtr = ::std::shared_ptr<Worker>;
using WorkerPrxPtr = ::std::shared_ptr<WorkerPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace WordCounter
{

class Worker;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< Worker>&);
::IceProxy::Ice::Object* upCast(Worker*);
/// \endcond

}

}

namespace WordCounter
{

class Worker;
/// \cond INTERNAL
::Ice::Object* upCast(Worker*);
/// \endcond
typedef ::IceInternal::Handle< Worker> WorkerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::WordCounter::Worker> WorkerPrx;
typedef WorkerPrx WorkerPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(WorkerPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace WordCounter
{

typedef ::std::vector< ::std::string> StringList;

typedef ::std::map< ::std::string, ::Ice::Int> WordCountMap;

struct SearchResult
{
    ::WordCounter::WordCountMap counts;
    ::WordCounter::StringList contexts;
};

}

namespace WordCounter
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::WordCounter::Worker::begin_searchWordsWithContext.
 * Create a wrapper instance by calling ::WordCounter::newCallback_Worker_searchWordsWithContext.
 */
class Callback_Worker_searchWordsWithContext_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Worker_searchWordsWithContext_Base> Callback_Worker_searchWordsWithContextPtr;

}

namespace IceProxy
{

namespace WordCounter
{

class Worker : public virtual ::Ice::Proxy<Worker, ::IceProxy::Ice::Object>
{
public:

    ::WordCounter::SearchResult searchWordsWithContext(const ::std::string& chunk, const ::WordCounter::StringList& words, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_searchWordsWithContext(_iceI_begin_searchWordsWithContext(chunk, words, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_searchWordsWithContext(const ::std::string& chunk, const ::WordCounter::StringList& words, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_searchWordsWithContext(chunk, words, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_searchWordsWithContext(const ::std::string& chunk, const ::WordCounter::StringList& words, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_searchWordsWithContext(chunk, words, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_searchWordsWithContext(const ::std::string& chunk, const ::WordCounter::StringList& words, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_searchWordsWithContext(chunk, words, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_searchWordsWithContext(const ::std::string& chunk, const ::WordCounter::StringList& words, const ::WordCounter::Callback_Worker_searchWordsWithContextPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_searchWordsWithContext(chunk, words, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_searchWordsWithContext(const ::std::string& chunk, const ::WordCounter::StringList& words, const ::Ice::Context& context, const ::WordCounter::Callback_Worker_searchWordsWithContextPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_searchWordsWithContext(chunk, words, context, cb, cookie);
    }

    ::WordCounter::SearchResult end_searchWordsWithContext(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_searchWordsWithContext(const ::std::string&, const ::WordCounter::StringList&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace WordCounter
{

class Worker : public virtual ::Ice::Object
{
public:

    typedef WorkerPrx ProxyType;
    typedef WorkerPtr PointerType;

    virtual ~Worker();

#ifdef ICE_CPP11_COMPILER
    Worker() = default;
    Worker(const Worker&) = default;
    Worker& operator=(const Worker&) = default;
#endif

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual SearchResult searchWordsWithContext(const ::std::string& chunk, const StringList& words, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_searchWordsWithContext(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const Worker& lhs, const Worker& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const Worker& lhs, const Worker& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::WordCounter::SearchResult>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 2;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::WordCounter::SearchResult, S>
{
    static void write(S* ostr, const ::WordCounter::SearchResult& v)
    {
        ostr->write(v.counts);
        ostr->write(v.contexts);
    }
};

template<typename S>
struct StreamReader< ::WordCounter::SearchResult, S>
{
    static void read(S* istr, ::WordCounter::SearchResult& v)
    {
        istr->read(v.counts);
        istr->read(v.contexts);
    }
};

}
/// \endcond

namespace WordCounter
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::WordCounter::Worker::begin_searchWordsWithContext.
 * Create a wrapper instance by calling ::WordCounter::newCallback_Worker_searchWordsWithContext.
 */
template<class T>
class CallbackNC_Worker_searchWordsWithContext : public Callback_Worker_searchWordsWithContext_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const SearchResult&);

    CallbackNC_Worker_searchWordsWithContext(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        WorkerPrx proxy = WorkerPrx::uncheckedCast(result->getProxy());
        SearchResult ret;
        try
        {
            ret = proxy->end_searchWordsWithContext(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::WordCounter::Worker::begin_searchWordsWithContext.
 */
template<class T> Callback_Worker_searchWordsWithContextPtr
newCallback_Worker_searchWordsWithContext(const IceUtil::Handle<T>& instance, void (T::*cb)(const SearchResult&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Worker_searchWordsWithContext<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::WordCounter::Worker::begin_searchWordsWithContext.
 */
template<class T> Callback_Worker_searchWordsWithContextPtr
newCallback_Worker_searchWordsWithContext(T* instance, void (T::*cb)(const SearchResult&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Worker_searchWordsWithContext<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::WordCounter::Worker::begin_searchWordsWithContext.
 * Create a wrapper instance by calling ::WordCounter::newCallback_Worker_searchWordsWithContext.
 */
template<class T, typename CT>
class Callback_Worker_searchWordsWithContext : public Callback_Worker_searchWordsWithContext_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const SearchResult&, const CT&);

    Callback_Worker_searchWordsWithContext(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        WorkerPrx proxy = WorkerPrx::uncheckedCast(result->getProxy());
        SearchResult ret;
        try
        {
            ret = proxy->end_searchWordsWithContext(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::WordCounter::Worker::begin_searchWordsWithContext.
 */
template<class T, typename CT> Callback_Worker_searchWordsWithContextPtr
newCallback_Worker_searchWordsWithContext(const IceUtil::Handle<T>& instance, void (T::*cb)(const SearchResult&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Worker_searchWordsWithContext<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::WordCounter::Worker::begin_searchWordsWithContext.
 */
template<class T, typename CT> Callback_Worker_searchWordsWithContextPtr
newCallback_Worker_searchWordsWithContext(T* instance, void (T::*cb)(const SearchResult&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Worker_searchWordsWithContext<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
