version: "3.9"

services:
  maestro:
    build:
      context: .
      dockerfile: maestro/Dockerfile
    container_name: maestro
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./texts:/app/texts
      - /tmp/chunks:/app/chunks
      - ./referencias:/app/referencias
      - ./shared:/app/shared
    depends_on:
      - nodo_java_1
      - nodo_java_2
      - nodo_java_3
      - nodo_java_4
    networks:
      - ice_network

  nodo_java_1:
    build:
      context: .
      dockerfile: nodo_java/Dockerfile
    container_name: nodo_java_1
    environment:
      - WORKER_NAME=JavaWorker1
    volumes:
      - ./texts:/app/texts
      - /tmp/chunks:/app/chunks
      - ./results:/app/results
      - ./shared:/app/shared
    expose:
      - "10000"
    networks:
      - ice_network

  nodo_java_2:
    build:
      context: .
      dockerfile: nodo_java/Dockerfile
    container_name: nodo_java_2
    environment:
      - WORKER_NAME=JavaWorker2
    volumes:
      - ./texts:/app/texts
      - /tmp/chunks:/app/chunks
      - ./results:/app/results
      - ./shared:/app/shared
    expose:
      - "10000"
    networks:
      - ice_network

  nodo_java_3:
    build:
      context: .
      dockerfile: nodo_java/Dockerfile
    container_name: nodo_java_3
    environment:
      - WORKER_NAME=JavaWorker3
    volumes:
      - ./texts:/app/texts
      - /tmp/chunks:/app/chunks
      - ./results:/app/results
      - ./shared:/app/shared
    expose:
      - "10000"
    networks:
      - ice_network

  nodo_java_4:
    build:
      context: .
      dockerfile: nodo_java/Dockerfile
    container_name: nodo_java_4
    environment:
      - WORKER_NAME=JavaWorker4
    volumes:
      - ./texts:/app/texts
      - /tmp/chunks:/app/chunks
      - ./results:/app/results
      - ./shared:/app/shared
    expose:
      - "10000"
    networks:
      - ice_network

networks:
  ice_network:
    driver: bridge
