//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `WordCount.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package WordCounter;

public class SearchResult implements java.lang.Cloneable,
                                     java.io.Serializable
{
    public java.util.Map<java.lang.String, java.lang.Integer> counts;

    public String[] contexts;

    public SearchResult()
    {
    }

    public SearchResult(java.util.Map<java.lang.String, java.lang.Integer> counts, String[] contexts)
    {
        this.counts = counts;
        this.contexts = contexts;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SearchResult r = null;
        if(rhs instanceof SearchResult)
        {
            r = (SearchResult)rhs;
        }

        if(r != null)
        {
            if(this.counts != r.counts)
            {
                if(this.counts == null || r.counts == null || !this.counts.equals(r.counts))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.contexts, r.contexts))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::WordCounter::SearchResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, counts);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, contexts);
        return h_;
    }

    public SearchResult clone()
    {
        SearchResult c = null;
        try
        {
            c = (SearchResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        WordCountMapHelper.write(ostr, this.counts);
        ostr.writeStringSeq(this.contexts);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.counts = WordCountMapHelper.read(istr);
        this.contexts = istr.readStringSeq();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SearchResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SearchResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        SearchResult v = new SearchResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SearchResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SearchResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<SearchResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(SearchResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SearchResult _nullMarshalValue = new SearchResult();

    /** @hidden */
    public static final long serialVersionUID = -156621085407035414L;
}
